package voicegateway

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/gin-gonic/gin"

	"github.com/FluentWork/fluentwork-backend/internal/conversation"
)

// stubLadderLLM stands in for the model behind app-server's rescue handler.
type stubLadderLLM struct {
	body string
}

func (s stubLadderLLM) Complete(_ context.Context, _ string, _ conversation.CompletionOptions) (string, error) {
	return s.body, nil
}

// ladderServer runs app-server's real rescue route, so these tests exercise the
// wire contract itself rather than a second opinion about it.
//
// The reason is a bug that survived every unit test here: the client decoded
// {"data":{"text":...}}, app-server sends {"level":N,"text":"..."}, and the
// test built the same wrong body the client expected — so it agreed with the
// bug. Hand-rolled response fixtures cannot catch this class of mistake; the
// handler that writes the response can.
func ladderServer(t *testing.T, llmText string) *httptest.Server {
	t.Helper()
	gin.SetMode(gin.TestMode)
	engine := gin.New()
	conversation.RegisterInternalRoutes(
		engine.Group("/internal/v1"),
		conversation.NewHandler(conversation.NewRescueGenerator(stubLadderLLM{body: llmText}), nil),
		"tok",
	)
	server := httptest.NewServer(engine)
	t.Cleanup(server.Close)
	return server
}

// The ladder is generated by app-server (方案 B): the client sends the rung and
// the conversation, and returns the text the orchestrator will speak.
func TestHTTPRescueGenerator_SendsTheRungAndReturnsTheText(t *testing.T) {
	var gotBody rescueLadderBody
	var gotToken string
	server := ladderServer(t, "先说结论，再说原因")
	// The recorder sits in front of the real route: the request is captured on
	// its way to the handler that will answer it, so what the client sends and
	// what the server replies are observed in one round trip.
	inner := server.Config.Handler
	server.Config.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/internal/v1/rescue/ladder" {
			t.Errorf("path = %s", r.URL.Path)
		}
		gotToken = r.Header.Get("X-Internal-Token")
		raw, _ := io.ReadAll(r.Body)
		// Re-seat the body: reading it here must not be what the handler sees.
		r.Body = io.NopCloser(strings.NewReader(string(raw)))
		if err := json.Unmarshal(raw, &gotBody); err != nil {
			t.Errorf("decode body: %v", err)
		}
		inner.ServeHTTP(w, r)
	})

	gen := NewHTTPRescueGenerator(server.URL, "tok", nil)
	text, err := gen.GenerateRescue(context.Background(), conversation.RescueHint, conversation.ConversationContext{
		LastAIMessage:   "What is blocking the release?",
		ScenarioContext: "standup",
		UserRole:        "Backend Engineer",
		RecentTurns:     []conversation.Turn{{Speaker: "ai", Content: "hi"}},
		SessionID:       "s1", UserID: "u1", TurnID: "t1",
	})
	if err != nil {
		t.Fatalf("GenerateRescue: %v", err)
	}
	if text != "先说结论，再说原因" {
		t.Fatalf("text = %q", text)
	}
	if gotToken != "tok" {
		t.Fatalf("token = %q", gotToken)
	}
	if gotBody.Level != int(conversation.RescueHint) || gotBody.SessionID != "s1" ||
		gotBody.UserID != "u1" || gotBody.TurnID != "t1" {
		t.Fatalf("body = %+v", gotBody)
	}
	if len(gotBody.RecentTurns) != 1 || gotBody.RecentTurns[0].Content != "hi" {
		t.Fatalf("recent turns = %+v", gotBody.RecentTurns)
	}
}

// Every failure returns an error, never a substitute: the orchestrator's static
// library is the fallback, and it must be the only one.
func TestHTTPRescueGenerator_FailuresReturnErrors(t *testing.T) {
	// Bodies are built from the server's own response type, never hand-written —
	// a fixture that spells the shape out is a second declaration of it, and the
	// last one of those was wrong.
	okBody := func(t *testing.T, rung conversation.LadderResponse) string {
		t.Helper()
		raw, err := json.Marshal(rung)
		if err != nil {
			t.Fatalf("marshal: %v", err)
		}
		return string(raw)
	}

	cases := []struct {
		name    string
		status  int
		body    string
		wantErr string
	}{
		{"model unavailable", http.StatusServiceUnavailable, `{"error":{"code":"unavailable"}}`, "http=503"},
		{"empty text", http.StatusOK, okBody(t, conversation.LadderResponse{Level: 1, Text: "   "}), "empty"},
		{"malformed envelope", http.StatusOK, `not json`, "decode"},
		{"a rung we did not ask for", http.StatusOK, okBody(t, conversation.LadderResponse{Level: 3, Text: "I think we should consider the trade-offs carefully."}), "level = 3, asked for 1"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
				w.WriteHeader(tc.status)
				_, _ = w.Write([]byte(tc.body))
			}))
			defer server.Close()

			gen := NewHTTPRescueGenerator(server.URL, "tok", nil)
			_, err := gen.GenerateRescue(context.Background(), conversation.RescueSkeleton,
				conversation.ConversationContext{SessionID: "s1"})
			if err == nil {
				t.Fatal("expected an error")
			}
			if !strings.Contains(err.Error(), tc.wantErr) {
				t.Fatalf("err = %v, want %q", err, tc.wantErr)
			}
		})
	}

	// An unconfigured client fails fast rather than calling anything.
	if _, err := NewHTTPRescueGenerator("", "tok", nil).GenerateRescue(
		context.Background(), conversation.RescueSkeleton, conversation.ConversationContext{}); err == nil {
		t.Fatal("an unconfigured client must error")
	}
}

// The client's own timeout sits inside the ladder budget, so a slow app-server
// hands control back to the fallback before the next rung is due.
func TestHTTPRescueGenerator_TimeoutFitsTheLadderBudget(t *testing.T) {
	gen := NewHTTPRescueGenerator("http://127.0.0.1:1", "tok", nil)
	if gen.Client.Timeout >= DefaultRescueLevel1After {
		t.Fatalf("client timeout %s must stay under the %s ladder budget", gen.Client.Timeout, DefaultRescueLevel1After)
	}
}
